export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const FILTER_TEXT_ARTICLE = 'FILTER_TEXT_ARTICLE'

export const FILTER_DATE_ARTICLE = 'FILTER_DATE_ARTICLE'